---
- name: Create and configure instances
  hosts:
    - all
  gather_facts: false
  roles:
    - role: ec2_instance
      ami_owner: 764336703387  # AlmaLinux OS
      ami_name_glob: "AlmaLinux OS 10.* aarch64"
      instance_type: "{{ linux_instance_type }}"
  tasks:
    - name: Setup instance facts
      ansible.builtin.set_fact:
        ansible_connection: amazon.aws.aws_ssm
        ansible_host: "{{ instance_id }}"
        ansible_aws_ssm_region: "{{ az_info.availability_zones[0].region_name }}"
        ansible_aws_ssm_bucket_name: "{{ lookup('env', 'SSM_BUCKET') }}"
        ansible_aws_ssm_retries: 5
      vars:
        instance_id: "{{ ec2_instance.instances[0].instance_id }}"

    - name: Wait for instance to be ready
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

    - name: Install Nginx
      become: true
      ansible.builtin.dnf:
        name:
          - nginx

    - name: Start and enable Nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Create web page
      become: true
      ansible.builtin.template:
        dest: /usr/share/nginx/html/index.html
        src: index.html.j2
        mode: '0644'

    - name: Show IP address of the instance
      ansible.builtin.debug:
        msg: "Instance {{ ec2_instance.instances[0].instance_id }} is running at IP {{ ec2_instance.instances[0].public_ip_address }}"
